export const events = [
  {
    image: "/images/event1.png",
    title: "Hackathon 2024",
    slug: "hackathon-2024",
    location: "Oslo, Norway",
    date: "2024-09-15",
    time: "10:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "Dev Conference",
    slug: "dev-conference",
    location: "San Francisco, USA",
    date: "2024-10-20",
    time: "9:00 AM",
  },
  {
    image: "/images/event3.png",
    title: "Tech Meetup",
    slug: "tech-meetup",
    location: "Berlin, Germany",
    date: "2024-11-05",
    time: "6:00 PM",
  },
  {
    image: "/images/event4.png",
    title: "Open Source Summit",
    slug: "open-source-summit",
    location: "Toronto, Canada",
    date: "2025-02-10",
    time: "9:30 AM",
  },
  {
    image: "/images/event5.png",
    title: "AI & ML Expo",
    slug: "ai-ml-expo",
    location: "Seoul, South Korea",
    date: "2025-03-18",
    time: "11:00 AM",
  },
  {
    image: "/images/event6.png",
    title: "Frontend Masters Day",
    slug: "frontend-masters-day",
    location: "London, UK",
    date: "2025-04-22",
    time: "10:00 AM",
  },
  {
    image: "/images/event4.png",
    title: "Cloud Native Workshop",
    slug: "cloud-native-workshop",
    location: "Dublin, Ireland",
    date: "2025-05-12",
    time: "1:00 PM",
  },
  {
    image: "/images/event5.png",
    title: "Design Systems Conf",
    slug: "design-systems-conf",
    location: "Amsterdam, Netherlands",
    date: "2025-06-03",
    time: "9:00 AM",
  },
  {
    image: "/images/event6.png",
    title: "Security in DevOps",
    slug: "security-in-devops",
    location: "Austin, USA",
    date: "2025-07-14",
    time: "2:00 PM",
  },
  {
    image: "/images/event1.png",
    title: "Mobile Dev Summit",
    slug: "mobile-dev-summit",
    location: "Sydney, Australia",
    date: "2025-08-21",
    time: "10:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "Startup Pitch Night",
    slug: "startup-pitch-night",
    location: "New York, USA",
    date: "2025-09-09",
    time: "6:00 PM",
  },
  {
    image: "/images/event3.png",
    title: "Data Engineering Meetup",
    slug: "data-engineering-meetup",
    location: "Toronto, Canada",
    date: "2025-10-05",
    time: "5:30 PM",
  },
  {
    image: "/images/event4.png",
    title: "Women in Tech Roundtable",
    slug: "women-in-tech-roundtable",
    location: "Madrid, Spain",
    date: "2025-11-11",
    time: "4:00 PM",
  },
];

export default events;
